In [27]:
import numpy as np
import pandas as pd

In [28]:
dataset_train = pd.read_csv("train.csv")
dataset_test = pd.read_csv("test.csv")

# New Section

In [29]:
dataset_train.info()
dataset_train.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [31]:
dataset_test.info()
dataset_test.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  418 non-null    int64  
 1   Pclass       418 non-null    int64  
 2   Name         418 non-null    object 
 3   Sex          418 non-null    object 
 4   Age          332 non-null    float64
 5   SibSp        418 non-null    int64  
 6   Parch        418 non-null    int64  
 7   Ticket       418 non-null    object 
 8   Fare         417 non-null    float64
 9   Cabin        91 non-null     object 
 10  Embarked     418 non-null    object 
dtypes: float64(2), int64(4), object(5)
memory usage: 36.0+ KB


PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male   
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female   
2          894       2                     Myles, Mr. Thomas Francis    male   
3          895       3                              Wirz, Mr. Albert    male   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   

    Age  SibSp  Parch   Ticket     Fare Cabin Embarked  
0  34.5      0      0   330911   7.8292   NaN        Q  
1  47.0      1      0   363272   7.0000   NaN        S  
2  62.0      0      0   240276   9.6875   NaN        Q  
3  27.0      0      0   315154   8.6625   NaN        S  
4  22.0      1      1  3101298  12.2875   NaN        S

## **Createing the Train set and the Test set**

In [32]:
from sklearn.model_selection import train_test_split
X = dataset_train[['Pclass','Sex','Age','SibSp','Parch', 'Fare', 'Embarked']].copy()
y = dataset_train['Survived']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)
X_submission = dataset_test[['Pclass','Sex','Age','SibSp','Parch', 'Fare', 'Embarked']].copy()
X_train.head()

Pclass     Sex   Age  SibSp  Parch     Fare Embarked
331       1    male  45.5      0      0  28.5000        S
733       2    male  23.0      0      0  13.0000        S
382       3    male  32.0      0      0   7.9250        S
704       3    male  26.0      1      0   7.8542        S
813       3  female   6.0      4      2  31.2750        S

## **Data Preprocessing**

In [33]:
from sklearn.preprocessing import LabelEncoder
le_sex = LabelEncoder()
le_embarked = LabelEncoder()
X_train['Sex'] = le_sex.fit_transform(X_train['Sex']) # male is 1 and female is 0
X_test['Sex'] = le_sex.transform(X_test['Sex'])
X_train['Embarked'] = le_embarked.fit_transform(X_train['Embarked'])
X_test['Embarked'] = le_embarked.transform(X_test['Embarked'])
X_submission['Sex'] = le_sex.transform(X_submission['Sex'])
X_submission['Embarked'] = le_embarked.transform(X_submission['Embarked'])
X_train

Pclass  Sex   Age  SibSp  Parch      Fare  Embarked
331       1    1  45.5      0      0   28.5000         2
733       2    1  23.0      0      0   13.0000         2
382       3    1  32.0      0      0    7.9250         2
704       3    1  26.0      1      0    7.8542         2
813       3    0   6.0      4      2   31.2750         2
..      ...  ...   ...    ...    ...       ...       ...
106       3    0  21.0      0      0    7.6500         2
270       1    1   NaN      0      0   31.0000         2
860       3    1  41.0      2      0   14.1083         2
435       1    0  14.0      1      2  120.0000         2
102       1    1  21.0      0      1   77.2875         2

[712 rows x 7 columns]

In [34]:
X_train

Pclass  Sex   Age  SibSp  Parch      Fare  Embarked
331       1    1  45.5      0      0   28.5000         2
733       2    1  23.0      0      0   13.0000         2
382       3    1  32.0      0      0    7.9250         2
704       3    1  26.0      1      0    7.8542         2
813       3    0   6.0      4      2   31.2750         2
..      ...  ...   ...    ...    ...       ...       ...
106       3    0  21.0      0      0    7.6500         2
270       1    1   NaN      0      0   31.0000         2
860       3    1  41.0      2      0   14.1083         2
435       1    0  14.0      1      2  120.0000         2
102       1    1  21.0      0      1   77.2875         2

[712 rows x 7 columns]

In [35]:
from sklearn.impute import KNNImputer
imputer = KNNImputer(n_neighbors=20)
X_train2 = X_train.copy()
X_test2 = X_test.copy()
X_submission2 = X_submission.copy()
types = X_train.dtypes.apply(lambda x: x.name).to_dict()
X_train = pd.DataFrame(imputer.fit_transform(X_train2), columns = X_train.columns)
X_test = pd.DataFrame(imputer.transform(X_test2), columns = X_test.columns)
X_submission = pd.DataFrame(imputer.transform(X_submission2), columns=X_submission.columns)
X_train = X_train.astype(types)
X_test = X_test.astype(types)
X_submission = X_submission.astype(types)
print(X_train[X_train['Age'].isnull()], X_test[X_test['Age'].isnull()])
print(X_train[X_train['Fare'].isnull()], X_test[X_test['Fare'].isnull()])

Empty DataFrame
Columns: [Pclass, Sex, Age, SibSp, Parch, Fare, Embarked]
Index: [] Empty DataFrame
Columns: [Pclass, Sex, Age, SibSp, Parch, Fare, Embarked]
Index: []
Empty DataFrame
Columns: [Pclass, Sex, Age, SibSp, Parch, Fare, Embarked]
Index: [] Empty DataFrame
Columns: [Pclass, Sex, Age, SibSp, Parch, Fare, Embarked]
Index: []


In [36]:
X_train

Pclass  Sex   Age  SibSp  Parch      Fare  Embarked
0         1    1  45.5      0      0   28.5000         2
1         2    1  23.0      0      0   13.0000         2
2         3    1  32.0      0      0    7.9250         2
3         3    1  26.0      1      0    7.8542         2
4         3    0   6.0      4      2   31.2750         2
..      ...  ...   ...    ...    ...       ...       ...
707       3    0  21.0      0      0    7.6500         2
708       1    1  40.1      0      0   31.0000         2
709       3    1  41.0      2      0   14.1083         2
710       1    0  14.0      1      2  120.0000         2
711       1    1  21.0      0      1   77.2875         2

[712 rows x 7 columns]

In [37]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[['Age','Fare']] = sc.fit_transform(X_train[['Age', 'Fare']])
X_test[['Age', 'Fare']] = sc.transform(X_test[['Age', 'Fare']])
X_submission[['Age', 'Fare']] = sc.transform(X_submission[['Age', 'Fare']])

In [38]:
X_train

Pclass  Sex       Age  SibSp  Parch      Fare  Embarked
0         1    1  1.206120      0      0 -0.078684         2
1         2    1 -0.503913      0      0 -0.377145         2
2         3    1  0.180100      0      0 -0.474867         2
3         3    1 -0.275909      1      0 -0.476230         2
4         3    0 -1.795938      4      2 -0.025249         2
..      ...  ...       ...    ...    ...       ...       ...
707       3    0 -0.655916      0      0 -0.480162         2
708       1    1  0.795712      0      0 -0.030545         2
709       3    1  0.864113      2      0 -0.355804         2
710       1    0 -1.187926      1      2  1.683201         2
711       1    1 -0.655916      0      1  0.860748         2

[712 rows x 7 columns]

In [39]:
X_train.sample(10)

Pclass  Sex       Age  SibSp  Parch      Fare  Embarked
475       3    1  0.332103      0      0 -0.502387         2
333       1    1  1.852132      0      1  0.860748         2
233       2    0 -2.099943      1      1 -0.126823         2
120       3    0 -0.579914      0      0 -0.424962         2
567       3    0  0.104099      0      0 -0.460265         2
440       2    0  0.288402      0      0 -0.389661         1
407       3    1  0.268148      0      0 -0.348262         2
91        3    0 -2.175945      1      1 -0.413089         2
430       3    1 -0.123906      1      0 -0.322267         2
601       3    0 -1.187926      0      0 -0.476230         2

In [40]:
X_test.sample(10)

Pclass  Sex       Age  SibSp  Parch      Fare  Embarked
61        2    0 -1.263927      0      1 -0.251984         2
162       2    1  0.712110      0      0 -0.377145         2
43        3    1  0.077498      0      0 -0.478237         1
165       1    1  2.688148      0      1  0.565978         0
88        1    1  0.636109      0      0 -0.627467         2
80        3    1 -1.035923      4      1  0.136738         2
157       3    0 -0.169507      0      0 -0.477515         1
71        1    0 -0.883920      2      2  4.424713         0
150       3    1  0.075294      0      0 -0.459703         0
117       2    1  0.484106      0      0 -0.379552         0

# **Support Vector Machine Model**

In [41]:
from sklearn.svm import SVC
sv_classifier = SVC(kernel='linear')
sv_classifier.fit(X_train, y_train)

SVC(kernel='linear')

In [42]:
y_predicted_test_sv = sv_classifier.predict(X_test)
y_predicted_test_sv[0:10]

array([0, 0, 0, 1, 1, 1, 1, 0, 1, 1], dtype=int64)

In [43]:
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import cross_validate
from sklearn import metrics

scoring = ['accuracy', 'precision_macro', 'recall_macro', 'f1_macro']

scores = cross_validate(sv_classifier, X_train, y_train, scoring=scoring)
print(confusion_matrix(y_test, y_predicted_test_sv))
print("accuracy: {0:0.2f}\n \
       precision macro average: {1:0.2f}\n \
       recall macro average: {2:0.2f}\n \
       f1_score macro average: {3:0.2f}".format(
                                                scores['test_accuracy'].mean(), 
                                                scores['test_precision_macro'].mean(), 
                                                scores['test_recall_macro'].mean(), 
                                                scores['test_f1_macro'].mean()))

[[88 17]
 [22 52]]
accuracy: 0.79
precision macro average: 0.78
recall macro average: 0.76
f1_score macro average: 0.77


# **Logistic Regression Model**

In [44]:
from sklearn.linear_model import LogisticRegression
lr_classifier = LogisticRegression(random_state = 0)
lr_classifier.fit(X_train, y_train)

LogisticRegression(random_state=0)

In [45]:
y_predicted_test_lr = lr_classifier.predict(X_test)
y_predicted_test_lr[0:10]

array([0, 0, 0, 1, 1, 1, 1, 0, 1, 1], dtype=int64)

In [46]:
scores = cross_validate(lr_classifier, X_train, y_train, scoring=scoring)
print(confusion_matrix(y_test, y_predicted_test_lr))
print("accuracy: {0:0.2f}\n \
       precision macro average: {1:0.2f}\n \
       recall macro average: {2:0.2f}\n \
       f1_score macro average: {3:0.2f}".format(
                                                scores['test_accuracy'].mean(), 
                                                scores['test_precision_macro'].mean(), 
                                                scores['test_recall_macro'].mean(), 
                                                scores['test_f1_macro'].mean()))

[[91 14]
 [19 55]]
accuracy: 0.80
precision macro average: 0.79
recall macro average: 0.77
f1_score macro average: 0.78


# **Guassian Naive Bayes Model**

In [47]:
from sklearn.naive_bayes import GaussianNB
gnb_classifier = GaussianNB()
gnb_classifier.fit(X_train, y_train)

GaussianNB()

In [48]:
y_predicted_test_gnb = gnb_classifier.predict(X_test)
y_predicted_test_gnb[0:10]

array([0, 0, 0, 1, 1, 1, 1, 0, 1, 1], dtype=int64)

In [49]:
scores = cross_validate(gnb_classifier, X_train, y_train, scoring=scoring)
print(confusion_matrix(y_test, y_predicted_test_gnb))
print("accuracy: {0:0.2f}\n \
       precision macro average: {1:0.2f}\n \
       recall macro average: {2:0.2f}\n \
       f1_score macro average: {3:0.2f}".format(
                                                scores['test_accuracy'].mean(), 
                                                scores['test_precision_macro'].mean(), 
                                                scores['test_recall_macro'].mean(), 
                                                scores['test_f1_macro'].mean()))

[[82 23]
 [17 57]]
accuracy: 0.79
precision macro average: 0.78
recall macro average: 0.78
f1_score macro average: 0.78


# **Predicting the Test Set**

In [50]:
y_predicted_sv = sv_classifier.predict(X_submission)
y_predicted_lr = lr_classifier.predict(X_submission)
y_predicted_gnb = gnb_classifier.predict(X_submission)

In [51]:
# write on gender_submission.csv
size = dataset_test['PassengerId'].values.size
predicted_array = np.concatenate((dataset_test['PassengerId'].values.reshape((size,1)), y_predicted_sv.reshape((size,1)), y_predicted_lr.reshape((size,1)), y_predicted_gnb.reshape((size,1))), axis=1)
predicted_df = pd.DataFrame(predicted_array, columns=["PassengerId", "Survived_SVM", "Survived_LR","Survived_GNB"])
predicted_df.to_csv("gender_submission.csv")