In [ ]:
import numpy as np
import pandas as pd

In [ ]:
dataset_train = pd.read_csv("train.csv")
dataset_test = pd.read_csv("test.csv")
dataset_submission = pd.read_csv("gender_submission.csv")

# New Section

In [ ]:
dataset_train.info()
dataset_train.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0            1         0       3  ...   7.2500   NaN         S
1            2         1       1  ...  71.2833   C85         C
2            3         1       3  ...   7.9250   NaN         S
3            4         1       1  ...  53.1000  C123         S
4            5         0       3  ...   8.0500   NaN         S

[5 rows x 12 columns]

In [ ]:
dataset_test.info()
dataset_test.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  418 non-null    int64  
 1   Pclass       418 non-null    int64  
 2   Name         418 non-null    object 
 3   Sex          418 non-null    object 
 4   Age          332 non-null    float64
 5   SibSp        418 non-null    int64  
 6   Parch        418 non-null    int64  
 7   Ticket       418 non-null    object 
 8   Fare         417 non-null    float64
 9   Cabin        91 non-null     object 
 10  Embarked     418 non-null    object 
dtypes: float64(2), int64(4), object(5)
memory usage: 36.0+ KB


PassengerId  Pclass  ... Cabin Embarked
0          892       3  ...   NaN        Q
1          893       3  ...   NaN        S
2          894       2  ...   NaN        Q
3          895       3  ...   NaN        S
4          896       3  ...   NaN        S

[5 rows x 11 columns]

In [ ]:
dataset_submission.info()
dataset_submission.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  418 non-null    int64
 1   Survived     418 non-null    int64
dtypes: int64(2)
memory usage: 6.7 KB


PassengerId  Survived
0          892         0
1          893         1
2          894         0
3          895         0
4          896         1

## **Createing the Train set and the Test set**

In [ ]:
X_train = dataset_train[['Pclass','Sex','Age','SibSp','Parch', 'Fare', 'Embarked']].copy()
X_test = dataset_test[['Pclass','Sex','Age','SibSp','Parch', 'Fare', 'Embarked']].copy()
X_train.head()

Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0       3    male  22.0      1      0   7.2500        S
1       1  female  38.0      1      0  71.2833        C
2       3  female  26.0      0      0   7.9250        S
3       1  female  35.0      1      0  53.1000        S
4       3    male  35.0      0      0   8.0500        S

## **Data Preprocessing**

In [ ]:
from sklearn.preprocessing import LabelEncoder
le_sex = LabelEncoder()
le_embarked = LabelEncoder()
X_train['Sex'] = le_sex.fit_transform(X_train['Sex']) # male is 1 and female is 0
X_test['Sex'] = le_sex.transform(X_test['Sex'])
X_train['Embarked'] = le_embarked.fit_transform(X_train['Embarked'])
X_test['Embarked'] = le_embarked.transform(X_test['Embarked'])
X_train 

Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0         3    1  22.0      1      0   7.2500         2
1         1    0  38.0      1      0  71.2833         0
2         3    0  26.0      0      0   7.9250         2
3         1    0  35.0      1      0  53.1000         2
4         3    1  35.0      0      0   8.0500         2
..      ...  ...   ...    ...    ...      ...       ...
886       2    1  27.0      0      0  13.0000         2
887       1    0  19.0      0      0  30.0000         2
888       3    0   NaN      1      2  23.4500         2
889       1    1  26.0      0      0  30.0000         0
890       3    1  32.0      0      0   7.7500         1

[891 rows x 7 columns]

In [ ]:
from sklearn.impute import KNNImputer
imputer = KNNImputer(n_neighbors=20)
X_train2 = X_train.copy()
X_test2 = X_test.copy()
types = X_train.dtypes.apply(lambda x: x.name).to_dict()
X_train = pd.DataFrame(imputer.fit_transform(X_train2), columns = X_train.columns)
X_test = pd.DataFrame(imputer.transform(X_test2), columns = X_test.columns)
X_train = X_train.astype(types)
X_test = X_test.astype(types)
print(X_train[X_train['Age'].isnull()], X_test[X_test['Age'].isnull()])
print(X_train[X_train['Fare'].isnull()], X_test[X_test['Fare'].isnull()])

Empty DataFrame
Columns: [Pclass, Sex, Age, SibSp, Parch, Fare, Embarked]
Index: [] Empty DataFrame
Columns: [Pclass, Sex, Age, SibSp, Parch, Fare, Embarked]
Index: []
Empty DataFrame
Columns: [Pclass, Sex, Age, SibSp, Parch, Fare, Embarked]
Index: [] Empty DataFrame
Columns: [Pclass, Sex, Age, SibSp, Parch, Fare, Embarked]
Index: []


In [ ]:
X_train

Pclass  Sex     Age  SibSp  Parch     Fare  Embarked
0         3    1  22.000      1      0   7.2500         2
1         1    0  38.000      1      0  71.2833         0
2         3    0  26.000      0      0   7.9250         2
3         1    0  35.000      1      0  53.1000         2
4         3    1  35.000      0      0   8.0500         2
..      ...  ...     ...    ...    ...      ...       ...
886       2    1  27.000      0      0  13.0000         2
887       1    0  19.000      0      0  30.0000         2
888       3    0  24.275      1      2  23.4500         2
889       1    1  26.000      0      0  30.0000         0
890       3    1  32.000      0      0   7.7500         1

[891 rows x 7 columns]

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[['Age','Fare']] = sc.fit_transform(X_train[['Age', 'Fare']])
X_test[['Age', 'Fare']] = sc.transform(X_test[['Age', 'Fare']])

In [ ]:
X_train

Pclass  Sex       Age  SibSp  Parch      Fare  Embarked
0         3    1 -0.595990      1      0 -0.502445         2
1         1    0  0.616810      1      0  0.786845         0
2         3    0 -0.292790      0      0 -0.488854         2
3         1    0  0.389410      1      0  0.420730         2
4         3    1  0.389410      0      0 -0.486337         2
..      ...  ...       ...    ...    ...       ...       ...
886       2    1 -0.216990      0      0 -0.386671         2
887       1    0 -0.823390      0      0 -0.044381         2
888       3    0 -0.423545      1      2 -0.176263         2
889       1    1 -0.292790      0      0 -0.044381         0
890       3    1  0.162010      0      0 -0.492378         1

[891 rows x 7 columns]

In [ ]:
X_train.sample(10)

Pclass  Sex       Age  SibSp  Parch      Fare  Embarked
551       2    1 -0.216990      0      0 -0.124920         2
419       3    0 -1.505590      0      2 -0.162169         2
343       2    1 -0.368590      0      0 -0.386671         2
592       3    1  1.299009      0      0 -0.502445         2
85        3    0  0.237810      3      0 -0.329287         2
14        3    0 -1.202390      0      0 -0.490280         2
794       3    1 -0.368590      0      0 -0.489442         2
765       1    0  1.602209      1      0  0.921244         2
775       3    1 -0.899190      0      0 -0.492378         2
276       3    0  1.147409      0      0 -0.492378         2

In [ ]:
X_test.sample(10)

Pclass  Sex       Age  SibSp  Parch      Fare  Embarked
150       1    0 -0.520190      0      1  1.025945         0
378       1    1  1.905409      0      0  0.358313         2
67        1    1  1.299009      0      0  0.205289         2
122       1    0  0.389410      1      0  0.514357         0
253       3    1 -0.444390      0      0 -0.460666         2
72        3    0 -0.065390      0      0 -0.488854         2
8         3    0 -0.899190      0      0 -0.502864         0
77        1    0  1.905409      2      0 -0.130960         2
1         3    0  1.299009      1      0 -0.507479         2
314       1    0  1.905409      0      0  2.082512         0

# **Creating Dependent Variable**

In [ ]:
y_train = dataset_train['Survived']
y_test = dataset_submission['Survived']
y_train

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

# **Support Vector Machine Model**

In [ ]:
from sklearn.svm import SVC
sv_classifier = SVC(kernel='linear')
sv_classifier.fit(X_train, y_train)

SVC(kernel='linear')

In [ ]:
y_predicted_sv = sv_classifier.predict(X_test)
y_predicted_sv[0:10]

array([0, 1, 0, 0, 1, 0, 1, 0, 1, 0])

In [ ]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
print(confusion_matrix(y_test, y_predicted_sv))
print(classification_report(y_test, y_predicted_sv))

[[266   0]
 [  0 152]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       266
           1       1.00      1.00      1.00       152

    accuracy                           1.00       418
   macro avg       1.00      1.00      1.00       418
weighted avg       1.00      1.00      1.00       418



# **Logistic Regression Model**

In [ ]:
from sklearn.linear_model import LogisticRegression
lr_classifier = LogisticRegression(random_state = 0)
lr_classifier.fit(X_train, y_train)

LogisticRegression(random_state=0)

In [ ]:
y_predicted_lr = lr_classifier.predict(X_test)
y_predicted_lr[0:10]

array([0, 0, 0, 0, 1, 0, 1, 0, 1, 0])

In [ ]:
print(confusion_matrix(y_test, y_predicted_lr))
print(classification_report(y_test, y_predicted_lr))

[[251  15]
 [ 10 142]]
              precision    recall  f1-score   support

           0       0.96      0.94      0.95       266
           1       0.90      0.93      0.92       152

    accuracy                           0.94       418
   macro avg       0.93      0.94      0.94       418
weighted avg       0.94      0.94      0.94       418



# **Guassian Naive Bayes Model**

In [ ]:
from sklearn.naive_bayes import GaussianNB
gnb_classifier = GaussianNB()
gnb_classifier.fit(X_train, y_train)

GaussianNB()

In [ ]:
y_predicted_gnb = gnb_classifier.predict(X_test)
y_predicted_gnb[0:10]

array([0, 1, 0, 0, 1, 0, 1, 0, 1, 0])

In [ ]:
print(confusion_matrix(y_test, y_predicted_gnb))
print(classification_report(y_test, y_predicted_gnb))

[[231  35]
 [  8 144]]
              precision    recall  f1-score   support

           0       0.97      0.87      0.91       266
           1       0.80      0.95      0.87       152

    accuracy                           0.90       418
   macro avg       0.89      0.91      0.89       418
weighted avg       0.91      0.90      0.90       418

